default: &default
  url: <%= ENV["DATABASE_URL"] %> 
  timeout: 5000

development:
  <<: *default

# test:
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   database: db/test.sqlite3
#   timeout: 5000

production:
  <<: *default
  
